# Site settings
title: FOOD NOT FUD
email: your-email@domain.com
description: The plain text recipe database for hackers
baseurl: "https://vrtulspud.github.io/chowdown"
language: "en"
lang_direction: "ltr"
color: "#007FFF"
twitter_username: 
github_username:  vrtulspud

# Build settings
markdown: kramdown

permalink: /:title:output_ext

collections:
  components:
    output: true
  recipes:
    output: true

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
